### PR TITLE
Refactor rfid register by extracting methods

### PR DESCRIPTION
**Pull request by alexhartley**
This should still all work as before but I can't test it without the Arduino. It's easier to
read I think now, and removes some duplicated code.

### CODE REVIEW

**Comment by pacharanero** [comment]
@phyushin this refactoring looks to be sensible, are you happy to merge?

**Comment by phyushin** [comment]
@alexhartley - the update_card method should probably be called something else like "sign_out" because it's not actually updating the card but yea those changes look good - ill pop down HS after work and test them out and then I'll merge :)

**Comment by alexhartley** [comment]
What time do you finish at @phyushin ? I might call in.

**Comment by phyushin** [comment]
1700

**Comment by phyushin** [comment]
I tested changes , seem to work ok ... commencing merge

**Pull request merged**
